query Projects($id: ID! = 1) {
    Projects_by_id(id: $id) {
        id
        name
        favorite
    }
    Projects @list(name:"FavoriteSpecies") {
        id
        name
        favorite
    }
}